logging:
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lxw?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 12345678
    tomcat:
      initial-size: 2
      max-active: 5
    mybatis:
      mapper-locations:classpath:mybatis/*.xml